language: java

jdk:
  - openjdk14

sudo: false

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="13a9775a-4677-47c1-a3c6-f8339cb045cc"

notifications:
  email:
    recipients:
      - anatoliy.gromov.service@gmail.com
    on_success: never # default: change
    on_failure: always # default: always